name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive' # Add this line to ensure submodules are also checked out
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Update to Node.js 16
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name YunHaaaa
          git config user.email qlxqlrt2012@gmail.com
          git add -A .
          git commit -m "generated"
          git push
